name: Build and test

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: pnpm/action-setup@v2
      with:
          version: 9
    - name: Install dependencies
      run: pnpm install
    - name: Build qm-ts
      run: pnpm -r build
    - name: Test qm-ts
      run: pnpm -r test -- --run
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qm-ts-build
        path: |
          packages/utils/dist
          packages/entityid/dist
  publish:
    if: startsWith( github.ref, 'refs/tags/v' )
    uses: ./.github/workflows/publish.yaml
    needs: ci
    secrets: inherit